### ISSUE TITLE
Properly handle duplicated test case names in programming exercises

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#1179]
### Describe the bug
If the CI systems includes duplicated entries for test case names, Artemis cannot handle this, because it needs to uniquely identify the test case name referenced in the problem statement.

Another problem is when the upper and lowercase change in the test case name, most probably because database keys need to be unique independent of upper and lowercase. This leads to the following exception and leaves instructors in a situation where they don't know what's going on.

```
Jan 08 16:38:00 vmbruegge106 java[698]: 2020-01-08 16:38:00.102  INFO 698 --- [nio-8080-exec-2] d.t.i.w.a.s.ProgrammingSubmissionService : create new programmingSubmission with commitHash: f449725ed82b22d8353e41925cd278983bf5bb6c for participation 278636
Jan 08 16:38:00 vmbruegge106 java[698]: 2020-01-08 16:38:00.240  WARN 698 --- [io-8080-exec-33] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1062, SQLState: 23000
Jan 08 16:38:00 vmbruegge106 java[698]: 2020-01-08 16:38:00.240 ERROR 698 --- [io-8080-exec-33] o.h.engine.jdbc.spi.SqlExceptionHelper   : Duplicate entry 'testInput_1-1024' for key 'exercise_test_case'
Jan 08 16:38:00 vmbruegge106 java[698]: 2020-01-08 16:38:00.242 ERROR 698 --- [io-8080-exec-33] o.z.problem.spring.common.AdviceTraits   : Internal Server Error
Jan 08 16:38:00 vmbruegge106 java[698]: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [exercise_test_case]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:297)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:254)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:528)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:153)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:144)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$ExposeRepositoryInvocationInterceptor.invoke(CrudMethodMetadataPostProcessor.java:364)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
Jan 08 16:38:00 vmbruegge106 java[698]:         at com.sun.proxy.$Proxy313.saveAll(Unknown Source)
Jan 08 16:38:00 vmbruegge106 java[698]:         at de.tum.in.www1.artemis.service.ProgrammingExerciseTestCaseService.generateTestCasesFromFeedbacks(ProgrammingExerciseTestCaseService.java:137)
Jan 08 16:38:00 vmbruegge106 java[698]:         at de.tum.in.www1.artemis.service.ProgrammingExerciseTestCaseService$$FastClassBySpringCGLIB$$626cab8e.invoke(<generated>)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
Jan 08 16:38:00 vmbruegge106 java[698]:         at de.tum.in.www1.artemis.service.ProgrammingExerciseTestCaseService$$EnhancerBySpringCGLIB$$c989a3db.generateTestCasesFromFeedbacks(<generated>)
Jan 08 16:38:00 vmbruegge106 java[698]:         at de.tum.in.www1.artemis.service.ResultService.extractTestCasesFromResult(ResultService.java:239)
Jan 08 16:38:00 vmbruegge106 java[698]:         at de.tum.in.www1.artemis.service.ResultService.processNewProgrammingExerciseResult(ResultService.java:180)
Jan 08 16:38:00 vmbruegge106 java[698]:         at de.tum.in.www1.artemis.service.ResultService$$FastClassBySpringCGLIB$$2023bc2c.invoke(<generated>)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
Jan 08 16:38:00 vmbruegge106 java[698]:         at de.tum.in.www1.artemis.service.ResultService$$EnhancerBySpringCGLIB$$9f972875.processNewProgrammingExerciseResult(<generated>)
Jan 08 16:38:00 vmbruegge106 java[698]:         at de.tum.in.www1.artemis.web.rest.ResultResource.notifyNewProgrammingExerciseResult(ResultResource.java:223)
Jan 08 16:38:00 vmbruegge106 java[698]:         at de.tum.in.www1.artemis.web.rest.ResultResource$$FastClassBySpringCGLIB$$86afbfd8.invoke(<generated>)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
Jan 08 16:38:00 vmbruegge106 java[698]:         at de.tum.in.www1.artemis.web.rest.ResultResource$$EnhancerBySpringCGLIB$$7d2ef316.notifyNewProgrammingExerciseResult(<generated>)
Jan 08 16:38:00 vmbruegge106 java[698]:         at jdk.internal.reflect.GeneratedMethodAccessor608.invoke(Unknown Source)
Jan 08 16:38:00 vmbruegge106 java[698]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Jan 08 16:38:00 vmbruegge106 java[698]:         at java.base/java.lang.reflect.Method.invoke(Method.java:567)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:893)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:798)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
Jan 08 16:38:00 vmbruegge106 java[698]:         at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
Jan 08 16:38:00 vmbruegge106 java[698]:         at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:97)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:209)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
Jan 08 16:38:00 vmbruegge106 java[698]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Jan 08 16:38:00 vmbruegge106 java[698]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
Jan 08 16:38:00 vmbruegge106 java[698]:         at java.base/java.lang.Thread.run(Thread.java:835)
Jan 08 16:38:00 vmbruegge106 java[698]: Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:59)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:178)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.dialect.identity.GetGeneratedKeysDelegate.executeAndExtract(GetGeneratedKeysDelegate.java:57)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:42)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3090)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3683)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:81)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:645)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:282)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:263)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:317)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:332)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:289)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:196)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:127)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:192)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:135)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:62)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:804)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:789)
Jan 08 16:38:00 vmbruegge106 java[698]:         at jdk.internal.reflect.GeneratedMethodAccessor591.invoke(Unknown Source)
Jan 08 16:38:00 vmbruegge106 java[698]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Jan 08 16:38:00 vmbruegge106 java[698]:         at java.base/java.lang.reflect.Method.invoke(Method.java:567)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:310)
Jan 08 16:38:00 vmbruegge106 java[698]:         at com.sun.proxy.$Proxy208.persist(Unknown Source)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.data.jpa.repository.support.SimpleJpaRepository.save(SimpleJpaRepository.java:535)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.data.jpa.repository.support.SimpleJpaRepository.saveAll(SimpleJpaRepository.java:567)
Jan 08 16:38:00 vmbruegge106 java[698]:         at jdk.internal.reflect.GeneratedMethodAccessor1014.invoke(Unknown Source)
Jan 08 16:38:00 vmbruegge106 java[698]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Jan 08 16:38:00 vmbruegge106 java[698]:         at java.base/java.lang.reflect.Method.invoke(Method.java:567)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:371)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:204)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:657)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:621)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:605)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
Jan 08 16:38:00 vmbruegge106 java[698]:         ... 98 common frames omitted
Jan 08 16:38:00 vmbruegge106 java[698]: Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'testInput_1-1024' for key 'exercise_test_case'
Jan 08 16:38:00 vmbruegge106 java[698]:         at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
Jan 08 16:38:00 vmbruegge106 java[698]:         at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
Jan 08 16:38:00 vmbruegge106 java[698]:         at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
Jan 08 16:38:00 vmbruegge106 java[698]:         at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:637)
Jan 08 16:38:00 vmbruegge106 java[698]:         at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:418)
Jan 08 16:38:00 vmbruegge106 java[698]:         at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
Jan 08 16:38:00 vmbruegge106 java[698]:         at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
Jan 08 16:38:00 vmbruegge106 java[698]:         at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
Jan 08 16:38:00 vmbruegge106 java[698]:         at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
Jan 08 16:38:00 vmbruegge106 java[698]:         at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
Jan 08 16:38:00 vmbruegge106 java[698]:         at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
Jan 08 16:38:00 vmbruegge106 java[698]:         at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
Jan 08 16:38:00 vmbruegge106 java[698]:         ... 139 common frames omitted
```

#### To Reproduce
1. Create a programming exercise with the default tests
2. Change one test to upper-case
3. Navigate to Manage test cases and notice that there are no active tests any more

#### Expected behavior
We should handle the upper and lower case problem by changing the existing test instead of creating a new one. This should be relatively easy.

It would also be good, if we can somehow notify the instructor (e.g. using an Artemis notification) when such a case occurs, because currently they do not really know what's going on.

Ideally, we should also handle the case when one build includes 2 identical test case names, e.g. by using the package and class name in addition and not only the method name of the test, however this might lead to problems when referencing the tests in the problem statement, so we should be careful that this functionality does not make existing functionality worse.

**Comment by krusche** [comment]
This issue has been fixed
