### ISSUE TITLE
Handle org.eclipse.jgit.api.errors.NoHeadException: Cannot check out from unborn branch.

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#1803]
During the git clone operation on the Artemis server for the setup of Programming Exercise Participations, it can potentially happen that the clone operation does not work, e.g. if 2 threads try to clone at the same time.

Then the use of the online code editor leads to an exception, when the Artemis server tries to pull the changes:

org.eclipse.jgit.api.errors.NoHeadException: Cannot check out from unborn branch
         at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:212)
         at de.tum.in.www1.artemis.service.connectors.GitService.pull(GitService.java:321)
         at de.tum.in.www1.artemis.service.connectors.GitService.getOrCheckoutRepository(GitService.java:142)
         at de.tum.in.www1.artemis.service.connectors.GitService.getOrCheckoutRepository(GitService.java:121)

**Comment by krusche** [comment]
we have already fixed this issue
