### ISSUE TITLE
In Jenkins test fail but Artemis claims they run through positively

### ISSUE THREAD

**Issue by axel1200** [ls1intum/Artemis#2244]
Funny thing I don't get the tests to fail :D

```
2020-10-20T18:55:20+02 Started by user Artemis User
2020-10-20T18:55:20+02 Running as SYSTEM
2020-10-20T18:55:20+02 Building in workspace /var/jenkins_home/workspace/ALPROHELLO/ALPROHELLO-BASE
2020-10-20T18:55:20+02 [WS-CLEANUP] Deleting project workspace...
2020-10-20T18:55:20+02 [WS-CLEANUP] Deferred wipeout is used...
2020-10-20T18:55:20+02 [WS-CLEANUP] Done
2020-10-20T18:55:20+02 The recommended git tool is: NONE
2020-10-20T18:55:20+02 using credential 70fd2abc-80e8-4382-b225-448c845a2326
2020-10-20T18:55:20+02 Cloning the remote Git repository
2020-10-20T18:55:20+02 Cloning repository https://gitlab.christiantiefenau.de/ALPROHELLO/alprohello-tests.git
2020-10-20T18:55:20+02  > git init /var/jenkins_home/workspace/ALPROHELLO/ALPROHELLO-BASE # timeout=10
2020-10-20T18:55:20+02 Fetching upstream changes from https://gitlab.christiantiefenau.de/ALPROHELLO/alprohello-tests.git
2020-10-20T18:55:20+02  > git --version # timeout=10
2020-10-20T18:55:20+02  > git --version # 'git version 2.11.0'
2020-10-20T18:55:20+02 using GIT_ASKPASS to set credentials Username and password of gitlab admin
2020-10-20T18:55:20+02  > git fetch --tags --progress -- https://gitlab.christiantiefenau.de/ALPROHELLO/alprohello-tests.git +refs/heads/*:refs/remotes/tests/* # timeout=10
2020-10-20T18:55:21+02  > git config remote.tests.url https://gitlab.christiantiefenau.de/ALPROHELLO/alprohello-tests.git # timeout=10
2020-10-20T18:55:21+02  > git config --add remote.tests.fetch +refs/heads/*:refs/remotes/tests/* # timeout=10
2020-10-20T18:55:21+02 Avoid second fetch
2020-10-20T18:55:21+02  > git rev-parse refs/remotes/tests/master^{commit} # timeout=10
2020-10-20T18:55:21+02 Checking out Revision 9503f14f0d0f8abb675406f3adb9a027f9e97db6 (refs/remotes/tests/master)
2020-10-20T18:55:21+02  > git config core.sparsecheckout # timeout=10
2020-10-20T18:55:21+02  > git checkout -f 9503f14f0d0f8abb675406f3adb9a027f9e97db6 # timeout=10
2020-10-20T18:55:21+02 Commit message: "Correct"
2020-10-20T18:55:21+02  > git rev-list --no-walk 9503f14f0d0f8abb675406f3adb9a027f9e97db6 # timeout=10
2020-10-20T18:55:21+02 The recommended git tool is: NONE
2020-10-20T18:55:21+02 using credential 70fd2abc-80e8-4382-b225-448c845a2326
2020-10-20T18:55:21+02 Cloning the remote Git repository
2020-10-20T18:55:21+02 Cloning repository https://gitlab.christiantiefenau.de/ALPROHELLO/alprohello-exercise.git
2020-10-20T18:55:21+02  > git init /var/jenkins_home/workspace/ALPROHELLO/ALPROHELLO-BASE/assignment # timeout=10
2020-10-20T18:55:21+02 Fetching upstream changes from https://gitlab.christiantiefenau.de/ALPROHELLO/alprohello-exercise.git
2020-10-20T18:55:21+02  > git --version # timeout=10
2020-10-20T18:55:21+02  > git --version # 'git version 2.11.0'
2020-10-20T18:55:21+02 using GIT_ASKPASS to set credentials Username and password of gitlab admin
2020-10-20T18:55:21+02  > git fetch --tags --progress -- https://gitlab.christiantiefenau.de/ALPROHELLO/alprohello-exercise.git +refs/heads/*:refs/remotes/assignment/* # timeout=10
2020-10-20T18:55:22+02  > git config remote.assignment.url https://gitlab.christiantiefenau.de/ALPROHELLO/alprohello-exercise.git # timeout=10
2020-10-20T18:55:22+02  > git config --add remote.assignment.fetch +refs/heads/*:refs/remotes/assignment/* # timeout=10
2020-10-20T18:55:22+02 Avoid second fetch
2020-10-20T18:55:22+02  > git rev-parse refs/remotes/assignment/master^{commit} # timeout=10
2020-10-20T18:55:22+02 Checking out Revision c1528096d6ceb4f5e5be3dd4d5aa54c347ef45da (refs/remotes/assignment/master)
2020-10-20T18:55:22+02  > git config core.sparsecheckout # timeout=10
2020-10-20T18:55:22+02  > git checkout -f c1528096d6ceb4f5e5be3dd4d5aa54c347ef45da # timeout=10
2020-10-20T18:55:22+02 Commit message: "Update HelloWorld.java"
2020-10-20T18:55:22+02  > git rev-list --no-walk c1528096d6ceb4f5e5be3dd4d5aa54c347ef45da # timeout=10
2020-10-20T18:55:22+02 [ALPROHELLO-BASE] $ mvn clean test
2020-10-20T18:55:23+02 WARNING: An illegal reflective access operation has occurred
2020-10-20T18:55:23+02 WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
2020-10-20T18:55:23+02 WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
2020-10-20T18:55:23+02 WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
2020-10-20T18:55:23+02 WARNING: All illegal access operations will be denied in a future release
2020-10-20T18:55:24+02 [INFO] Scanning for projects...
2020-10-20T18:55:24+02 [INFO]                                                                         
2020-10-20T18:55:24+02 [INFO] ------------------------------------------------------------------------
2020-10-20T18:55:24+02 [INFO] Building Hello World Tests 1.0
2020-10-20T18:55:24+02 [INFO] ------------------------------------------------------------------------
2020-10-20T18:55:24+02 [INFO] 
2020-10-20T18:55:24+02 [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ Hello-World-Tests ---
2020-10-20T18:55:24+02 [INFO] 
2020-10-20T18:55:24+02 [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Hello-World-Tests ---
2020-10-20T18:55:24+02 [INFO] Using 'UTF-8' encoding to copy filtered resources.
2020-10-20T18:55:24+02 [INFO] skip non existing resourceDirectory /var/jenkins_home/workspace/ALPROHELLO/ALPROHELLO-BASE/src/main/resources
2020-10-20T18:55:24+02 [INFO] 
2020-10-20T18:55:24+02 [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ Hello-World-Tests ---
2020-10-20T18:55:24+02 [INFO] Changes detected - recompiling the module!
2020-10-20T18:55:24+02 [INFO] Compiling 1 source file to /var/jenkins_home/workspace/ALPROHELLO/ALPROHELLO-BASE/target/classes
2020-10-20T18:55:25+02 [INFO] 
2020-10-20T18:55:25+02 [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ Hello-World-Tests ---
2020-10-20T18:55:25+02 [INFO] Using 'UTF-8' encoding to copy filtered resources.
2020-10-20T18:55:25+02 [INFO] Copying 1 resource
2020-10-20T18:55:25+02 [INFO] 
2020-10-20T18:55:25+02 [INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ Hello-World-Tests ---
2020-10-20T18:55:25+02 [INFO] Changes detected - recompiling the module!
2020-10-20T18:55:25+02 [INFO] Compiling 1 source file to /var/jenkins_home/workspace/ALPROHELLO/ALPROHELLO-BASE/target/test-classes
2020-10-20T18:55:25+02 [INFO] 
2020-10-20T18:55:25+02 [INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ Hello-World-Tests ---
2020-10-20T18:55:25+02 [INFO] 
2020-10-20T18:55:25+02 [INFO] -------------------------------------------------------
2020-10-20T18:55:25+02 [INFO]  T E S T S
2020-10-20T18:55:25+02 [INFO] -------------------------------------------------------
2020-10-20T18:55:26+02 [INFO] Running greeting.HelloWorldTest
2020-10-20T18:55:26+02 [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.072 s <<< FAILURE! - in greeting.HelloWorldTest
2020-10-20T18:55:26+02 [ERROR] testPrint(greeting.HelloWorldTest)  Time elapsed: 0.017 s  <<< FAILURE!
2020-10-20T18:55:26+02 java.lang.AssertionError
2020-10-20T18:55:26+02 	at greeting.HelloWorldTest.testPrint(HelloWorldTest.java:37)
2020-10-20T18:55:26+02 
2020-10-20T18:55:26+02 [INFO] 
2020-10-20T18:55:26+02 [INFO] Results:
2020-10-20T18:55:26+02 [INFO] 
2020-10-20T18:55:26+02 [ERROR] Failures: 
2020-10-20T18:55:26+02 [ERROR]   HelloWorldTest.testPrint:37
2020-10-20T18:55:26+02 [INFO] 
2020-10-20T18:55:26+02 [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
2020-10-20T18:55:26+02 [INFO] 
2020-10-20T18:55:26+02 [INFO] ------------------------------------------------------------------------
2020-10-20T18:55:26+02 [INFO] BUILD FAILURE
2020-10-20T18:55:26+02 [INFO] ------------------------------------------------------------------------
2020-10-20T18:55:26+02 [INFO] Total time: 2.416 s
2020-10-20T18:55:26+02 [INFO] Finished at: 2020-10-20T16:55:26+00:00
2020-10-20T18:55:26+02 [INFO] Final Memory: 16M/108M
2020-10-20T18:55:26+02 [INFO] ------------------------------------------------------------------------
2020-10-20T18:55:26+02 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project Hello-World-Tests: There are test failures.
2020-10-20T18:55:26+02 [ERROR] 
2020-10-20T18:55:26+02 [ERROR] Please refer to /var/jenkins_home/workspace/ALPROHELLO/ALPROHELLO-BASE/target/surefire-reports for the individual test results.
2020-10-20T18:55:26+02 [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
2020-10-20T18:55:26+02 [ERROR] -> [Help 1]
2020-10-20T18:55:26+02 [ERROR] 
2020-10-20T18:55:26+02 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
2020-10-20T18:55:26+02 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
2020-10-20T18:55:26+02 [ERROR] 
2020-10-20T18:55:26+02 [ERROR] For more information about the errors and possible solutions, please read the following articles:
2020-10-20T18:55:26+02 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
2020-10-20T18:55:26+02 Build step 'Invoke top-level Maven targets' marked build as failure
2020-10-20T18:55:26+02 Performing Post build task...
2020-10-20T18:55:26+02 Match found for :.* : True
2020-10-20T18:55:26+02 Logical operation result is TRUE
2020-10-20T18:55:26+02 Running script  : mkdir results
2020-10-20T18:55:26+02                     cp target/surefire-reports/*.xml $WORKSPACE/results/
2020-10-20T18:55:26+02 [ALPROHELLO-BASE] $ /bin/sh -xe /tmp/jenkins4439437951554289875.sh
2020-10-20T18:55:26+02 + mkdir results
2020-10-20T18:55:26+02 + cp target/surefire-reports/TEST-greeting.HelloWorldTest.xml /var/jenkins_home/workspace/ALPROHELLO/ALPROHELLO-BASE/results/
2020-10-20T18:55:26+02 POST BUILD TASK : SUCCESS
2020-10-20T18:55:26+02 END OF POST BUILD TASK : 0
2020-10-20T18:55:26+02 Finished: FAILURE
``` 
Obviously, the test failed

But then Artemis enters this into the result table:
![Screenshot from 2020-10-20 19-04-44](https://user-images.githubusercontent.com/19996713/96620029-2a481d00-1307-11eb-93c6-6fdeabd17e55.png)

**Comment by axel1200** [comment]
```xml
<testcase name="testPrint" classname="greeting.HelloWorldTest" time="0.017">
    <failure type="java.lang.AssertionError">java.lang.AssertionError
	at greeting.HelloWorldTest.testPrint(HelloWorldTest.java:37)
</failure>
  </testcase>
```
From XML file, from result folder (TEST-greeting.HelloWorldTest.xml)

**Comment by axel1200** [comment]
This might be related 
```
artemis                    | 2020-10-20 16:55:20.513  WARN 1 --- [nio-8080-exec-9] d.t.i.w.a.s.c.jenkins.JenkinsService     : Could not find pending ProgrammingSubmission for Commit-Hash Optional[c1528096d6ceb4f5e5be3dd4d5aa54c347ef45da] (Participation 13, Build-Plan ALPROHELLO-BASE). Will create a new one subsequently...
```

**Comment by axel1200** [comment]
So this is about the BASE repo of an exercise. Artemis shows that the base repo actually fulfills some tests and hence shows "!"
That's not true tho as you can see in the above log from Jenkins

**Comment by axel1200** [comment]
In the feedback table a postive feedback is entered for the test:
189,,testPrint,60,AUTOMATIC,true,0,10,,
![Screenshot from 2020-10-20 19-31-50](https://user-images.githubusercontent.com/19996713/96622990-f0791580-130a-11eb-8fb0-1653394ec39d.png)

**Comment by axel1200** [comment]
I triggered the builds by using Jenkins "Build now" button. But did not work before when I triggered it with commits...

**Comment by axel1200** [comment]
If I had to make a guess the Jenkins plugin report is faulty. What could I do to debug this :thinking:

**Comment by sleiss** [comment]
@axel1200 Can you maybe send me your exercise (template, solution, test) repositories (e.g. as archive)? I'll try to reproduce it on our instance then.

**Comment by axel1200** [comment]
So I deleted the old exercise and recreated it so was not a one time thing

**Comment by axel1200** [comment]
[alprohellocommand-tests.zip](https://github.com/ls1intum/Artemis/files/5410739/alprohellocommand-tests.zip)

**Comment by krusche** [comment]
Which programming language do you use?

**Comment by krusche** [comment]
We just updated the Jenkins plugin in the other repo. Do you have the newest version?

**Comment by krusche** [comment]
If it is related to this plugin, please add an issue in the other repository

**Comment by axel1200** [comment]
We use Java 
See https://github.com/ls1intum/Artemis/pull/2224 that probably explains it

**Comment by sleiss** [comment]
@krusche @axel1200 I was able to reproduce it on our instance.

**Comment by sleiss** [comment]
For reference: This is the payload sent from Jenkins to Artemis:

```
{
   "fullName":"TESTHELLOWORLD Â» TESTHELLOWORLD-ARTEMISADMIN #5",
   "successful":0,
   "skipped":0,
   "errors":0,
   "failures":1,
   "commits":[
      {
         "hash":"e846d0f0f3878f31f5279afcd4d7f8f1911b5ca5",
         "repositorySlug":"testhelloworld-tests"
      },
      {
         "hash":"cb8a7f57969af6006ab7449cad05c5c983821a20",
         "repositorySlug":"testhelloworld-artemis_admin"
      }
   ],
   "results":[
      {
         "name":"hello.HelloTest",
         "time":0.052,
         "errors":0,
         "skipped":0,
         "failures":1,
         "tests":1,
         "testCases":[
            {
               "name":"testHello",
               "classname":"hello.HelloTest",
               "time":0.006,
               "failures":[
                  {
                     "type":"java.lang.AssertionError"
                  }
               ]
            }
         ]
      }
   ],
   "staticCodeAnalysisReports":[
      
   ],
   "runDate":"2020-10-20T18:44:40.131Z[Etc/UTC]"
}
```

**Comment by sleiss** [comment]
@axel1200 I could verify that it indeed is related to #2224. If I add the test message, it works as expected.

Do you think we can this issue as we already track this in #2224?

In the meantime, I suggest adding the test error messages.

**Comment by krusche** [comment]
I'll close this here as I added another comment in #2224 
To summarize: Artemis assumes error messages in assert statements so that it can show feedback to students.

**Comment by krusche** [comment]
@axel1200 If you send me your email address to krusche@in.tum.de I can also invite you into our Slack channel
It might be easier to get some support there.
