### ISSUE TITLE
Faulty feedback on jenkins

### ISSUE THREAD

**Issue by axel1200** [ls1intum/Artemis#2345]
Ich bin mir nicht sicher ob https://github.com/ls1intum/Artemis/issues/2169 mit folgendem Fehler zu tun hat aber ich schreib es mal hier rein:

Auf Produktion läuft https://github.com/ls1intum/Artemis/issues/2169 rebased auf develop, zusammen mit anderen nicht zusammenhängenden benutzerdifinierten Änderungen.
Es gibt jetzt eine Aufgabe dort benutzen wir in den Tests die Klasse BehaviorTest, um dem Studenten sinnvolles Feedback zu geben, falls eine Klasse fehlt o.ä.

In dem folgendem Beispiel hat jemand die Main Methode Groß statt klein geschrieben:
![Screenshot from 2020-11-05 13-29-42](https://user-images.githubusercontent.com/19996713/98241273-ff96cf00-1f6a-11eb-888e-34aa48452605.png)
Der Jenkins output ist:
```
Downloaded from central: https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-launcher/1.3.2/junit-platform-launcher-1.3.2.jar (95 kB at 1.6 MB/s)
2020-11-05T13:09:47+01  Downloaded from central: https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-engine/1.3.2/junit-platform-engine-1.3.2.jar (138 kB at 2.2 MB/s)
2020-11-05T13:09:47+01  [INFO] 
2020-11-05T13:09:47+01  [INFO] -------------------------------------------------------
2020-11-05T13:09:47+01  [INFO]  T E S T S
2020-11-05T13:09:47+01  [INFO] -------------------------------------------------------
2020-11-05T13:09:47+01  [ERROR] Picked up JAVA_TOOL_OPTIONS: -Dmaven.ext.class.path="/var/jenkins_home/workspace/ALPROSTRINGCON/ALPROSTRINGCON-S6FEALCA@tmp/withMavenadc4f557/pipeline-maven-spy.jar" -Dorg.jenkinsci.plugins.pipeline.maven.reportsFolder="/var/jenkins_home/workspace/ALPROSTRINGCON/ALPROSTRINGCON-S6FEALCA@tmp/withMavenadc4f557" 
2020-11-05T13:09:47+01  [INFO] Running MainTest
2020-11-05T13:09:47+01  [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.066 s <<< FAILURE! - in MainTest
2020-11-05T13:09:47+01  [ERROR] MainTest.testOutput  Time elapsed: 0.043 s  <<< FAILURE!
2020-11-05T13:09:47+01  org.opentest4j.AssertionFailedError: Could not find the method 'main' with the parameters: [ String[] ] in the class Main because the method does not exist. Make sure to implement this method properly.
2020-11-05T13:09:47+01  	at MainTest.testOutput(MainTest.java:31)
2020-11-05T13:09:47+01  
2020-11-05T13:09:47+01  [INFO] 
2020-11-05T13:09:47+01  [INFO] Results:
2020-11-05T13:09:47+01  [INFO] 
2020-11-05T13:09:47+01  [ERROR] Failures: 
2020-11-05T13:09:47+01  [ERROR]   MainTest.testOutput:31->BehaviorTest.invokeMethod:261->BehaviorTest.getMethod:168->BehaviorTest.getMethod:189 Could not find the method 'main' with the parameters: [ String[] ] in the class Main because the method does not exist. Make sure to implement this method properly.
2020-11-05T13:09:47+01  [INFO] 
2020-11-05T13:09:47+01  [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
2020-11-05T13:09:47+01  [INFO] 
2020-11-05T13:09:47+01  [INFO] ------------------------------------------------------------------------
2020-11-05T13:09:47+01  [INFO] BUILD FAILURE
2020-11-05T13:09:47+01  [INFO] ------------------------------------------------------------------------
2020-11-05T13:09:47+01  [INFO] Total time:  10.176 s
2020-11-05T13:09:47+01  [INFO] Finished at: 2020-11-05T12:09:47Z
2020-11-05T13:09:47+01  [INFO] ------------------------------------------------------------------------
2020-11-05T13:09:47+01  [INFO] [jenkins-event-spy] Generated /var/jenkins_home/workspace/ALPROSTRINGCON/ALPROSTRINGCON-S6FEALCA@tmp/withMavenadc4f557/maven-spy-20201105-120937-450269038662599953396.log
2020-11-05T13:09:47+01  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project String-konkatinieren-Tests: There are test failures.
2020-11-05T13:09:47+01  [ERROR] 
2020-11-05T13:09:47+01  [ERROR] Please refer to /var/jenkins_home/workspace/ALPROSTRINGCON/ALPROSTRINGCON-S6FEALCA/target/surefire-reports for the individual test results.
2020-11-05T13:09:47+01  [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
2020-11-05T13:09:47+01  [ERROR] -> [Help 1]
2020-11-05T13:09:47+01  [ERROR] 
2020-11-05T13:09:47+01  [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
2020-11-05T13:09:47+01  [ERROR] Re-run Maven using the -X switch to enable full debug logging.
2020-11-05T13:09:47+01  [ERROR] 
2020-11-05T13:09:47+01  [ERROR] For more information about the errors and possible solutions, please read the following articles:
2020-11-05T13:09:47+01  [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```
Ich würde als Feedback erwarten:
```
Could not find the method 'main' with the parameters: [ String[] ] in the class Main because the method does not exist. Make sure to 
```
Statt dem Namen der Excpetion.

Selbiges gilt für alle anderen Assertions:
```
2020-11-05T13:03:48+01  [ERROR] Picked up JAVA_TOOL_OPTIONS: -Dmaven.ext.class.path="/var/jenkins_home/workspace/ALPROSTRINGCON/ALPROSTRINGCON-DATHEN@tmp/withMaven186a8fb5/pipeline-maven-spy.jar" -Dorg.jenkinsci.plugins.pipeline.maven.reportsFolder="/var/jenkins_home/workspace/ALPROSTRINGCON/ALPROSTRINGCON-DATHEN@tmp/withMaven186a8fb5" 
2020-11-05T13:03:48+01  [INFO] Running MainTest
2020-11-05T13:03:48+01  [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.086 s <<< FAILURE! - in MainTest
2020-11-05T13:03:48+01  [ERROR] MainTest.testOutput  Time elapsed: 0.064 s  <<< FAILURE!
2020-11-05T13:03:48+01  org.opentest4j.AssertionFailedError: Nachricht enthält nicht hallo ==> expected: <true> but was: <false>
2020-11-05T13:03:48+01  	at MainTest.testOutput(MainTest.java:34)
2020-11-05T13:03:48+01  
2020-11-05T13:03:48+01  [INFO] 
2020-11-05T13:03:48+01  [INFO] Results:
2020-11-05T13:03:48+01  [INFO] 
2020-11-05T13:03:48+01  [ERROR] Failures: 
2020-11-05T13:03:48+01  [ERROR]   MainTest.testOutput:34 Nachricht enthält nicht hallo ==> expected: <true> but was: <false>
2020-11-05T13:03:48+01  [INFO] 
2020-11-05T13:03:48+01  [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```
Also Feedback gibt es:
![Screenshot from 2020-11-05 13-36-11](https://user-images.githubusercontent.com/19996713/98241901-e5112580-1f6b-11eb-88e7-dde6a5c38f42.png)

Wie könnte ich dies debuggen? Gibt es neulich Änderungen, die dies verursachen könnten.

**Comment by axel1200** [comment]
Part of the report xml:
```
  <testcase name="testOutput" classname="MainTest" time="0.059">
    <failure type="org.opentest4j.AssertionFailedError"><![CDATA[org.opentest4j.AssertionFailedError: Nachricht enthält nicht hallo ==> expected: <true> but was: <false>
	at MainTest.testOutput(MainTest.java:34)
]]></failure>
  </testcase>
```

**Comment by axel1200** [comment]
This might explain it:
From reading the code I would have expected:
```
<failure type="org.opentest4j.AssertionFailedError" messageWithStackTrace="org.opentest4j.AssertionFailedError: Nachricht enthält nicht hallo ==> expected: <true> but was: <false>
	at MainTest.testOutput(MainTest.java:34)"></failure>
```
Because that is what the ErrorOrFailureDTO.class expects the xml to look like.
Question is why is it in the body of the failure Object.

**Comment by axel1200** [comment]
oh is the xml converted to json by the jenkins plugin :thinking: ?

**Comment by axel1200** [comment]
Ok my result is that the XML looks good and like it should. So now I am trying to get the json that is sent by the plugin

**Comment by krusche** [comment]
which junit and surefire version are you using?

**Comment by axel1200** [comment]
```
{
  "_class": "org.jenkinsci.plugins.workflow.job.WorkflowJob",
  "actions": [
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {
      "_class": "com.cloudbees.plugins.credentials.ViewCredentialsAction"
    }
  ],
  "description": "",
  "displayName": "ALPROSTRINGCON-XXX",
  "displayNameOrNull": null,
  "fullDisplayName": "ALPROSTRINGCON » ALPROSTRINGCON-XXX",
  "fullName": "ALPROSTRINGCON/ALPROSTRINGCON-XXX",
  "name": "ALPROSTRINGCON-XXX",
  "url": "https://jenkins.christiantiefenau.de/job/ALPROSTRINGCON/job/ALPROSTRINGCON-XXX/",
  "buildable": true,
  "builds": [
    {
      "_class": "org.jenkinsci.plugins.workflow.job.WorkflowRun",
      "number": 3,
      "url": "https://jenkins.christiantiefenau.de/job/ALPROSTRINGCON/job/ALPROSTRINGCON-XXX/3/"
    },
    {
      "_class": "org.jenkinsci.plugins.workflow.job.WorkflowRun",
      "number": 2,
      "url": "https://jenkins.christiantiefenau.de/job/ALPROSTRINGCON/job/ALPROSTRINGCON-XXX/2/"
    },
    {
      "_class": "org.jenkinsci.plugins.workflow.job.WorkflowRun",
      "number": 1,
      "url": "https://jenkins.christiantiefenau.de/job/ALPROSTRINGCON/job/ALPROSTRINGCON-XXX/1/"
    }
  ],
  "color": "red",
  "firstBuild": {
    "_class": "org.jenkinsci.plugins.workflow.job.WorkflowRun",
    "number": 1,
    "url": "https://jenkins.christiantiefenau.de/job/ALPROSTRINGCON/job/ALPROSTRINGCON-XXX/1/"
  },
  "healthReport": [
    {
      "description": "Test Result: 1 test failing out of a total of 1 test.",
      "iconClassName": "icon-health-00to19",
      "iconUrl": "health-00to19.png",
      "score": 0
    },
    {
      "description": "Build stability: All recent builds failed.",
      "iconClassName": "icon-health-00to19",
      "iconUrl": "health-00to19.png",
      "score": 0
    }
  ],
  "inQueue": false,
  "keepDependencies": false,
  "lastBuild": {
    "_class": "org.jenkinsci.plugins.workflow.job.WorkflowRun",
    "number": 3,
    "url": "https://jenkins.christiantiefenau.de/job/ALPROSTRINGCON/job/ALPROSTRINGCON-XXX/3/"
  },
  "lastCompletedBuild": {
    "_class": "org.jenkinsci.plugins.workflow.job.WorkflowRun",
    "number": 3,
    "url": "https://jenkins.christiantiefenau.de/job/ALPROSTRINGCON/job/ALPROSTRINGCON-XXX/3/"
  },
  "lastFailedBuild": {
    "_class": "org.jenkinsci.plugins.workflow.job.WorkflowRun",
    "number": 3,
    "url": "https://jenkins.christiantiefenau.de/job/ALPROSTRINGCON/job/ALPROSTRINGCON-XXX/3/"
  },
  "lastStableBuild": null,
  "lastSuccessfulBuild": null,
  "lastUnstableBuild": null,
  "lastUnsuccessfulBuild": {
    "_class": "org.jenkinsci.plugins.workflow.job.WorkflowRun",
    "number": 3,
    "url": "https://jenkins.christiantiefenau.de/job/ALPROSTRINGCON/job/ALPROSTRINGCON-XXX/3/"
  },
  "nextBuildNumber": 4,
  "property": [
    {
      "_class": "com.dabsquared.gitlabjenkins.connection.GitLabConnectionProperty"
    },
    {
      "_class": "org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty"
    }
  ],
  "queueItem": null,
  "concurrentBuild": true,
  "resumeBlocked": false
}
```

**Comment by axel1200** [comment]
Based on commit 9d43154e8b5dc990f84a65fb293622ade84c6674

**Comment by axel1200** [comment]
Updating the jenkins plugin to version 1.2.0 fixed it

**Comment by krusche** [comment]
Sorry for the trouble, I guess we should have communicated this better, that the new version is needed
