### ISSUE TITLE
SQL Exception in processNewProgrammingExerciseResult

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#2410]
We should handle the case and prevent 'NaN' values

```
Nov 11 16:44:13 node1 java[107140]: 2020-11-11 16:44:13.536 ERROR 107140 --- [nio-8080-exec-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : 'NaN' is not a valid numeric or approximate numeric value
Nov 11 16:44:13 node1 java[107140]: 2020-11-11 16:44:13.547 ERROR 107140 --- [nio-8080-exec-3] o.z.problem.spring.common.AdviceTraits   : Internal Server Error
Nov 11 16:44:13 node1 java[107140]: org.springframework.orm.jpa.JpaSystemException: could not insert: [de.tum.in.www1.artemis.domain.Feedback]; nested exception is org.hibernate.exception.GenericJDBCException: could not insert: [de.tum.in.www1.artemis.domain.Feedback]
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:353)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:255)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:528)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:154)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:178)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
Nov 11 16:44:13 node1 java[107140]:         at com.sun.proxy.$Proxy264.save(Unknown Source)
Nov 11 16:44:13 node1 java[107140]:         at de.tum.in.www1.artemis.service.ProgrammingExerciseGradingService.processNewProgrammingExerciseResult(ProgrammingExerciseGradingService.java:105)
```

**Comment by schultek** [comment]
I think this has to do with a 'null' value in the database for a test-case weight.

When entering a NaN value for a weight, this gets stored as null in the database, instead of the default value of 1.
Strangely, this does not happen for bonusMultiplier and bonusPoints. However, the related java code and database configuration seems to be the same for all fields. 
In fact, there are no java checks for null values in place, but all fields are configured in the database as 'Double' together with a default value.

**Comment by schultek** [comment]
To fix this, I could just add a java check to apply the default value. But I would like to understand why this works for the other fields and not for the weight.

**Comment by schultek** [comment]
This might be related to this liquibase changelog: (But I don't see how)
```xml
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:pro="http://www.liquibase.org/xml/ns/pro" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-3.9.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.9.xsd">
    <changeSet author="krusche" id="20200716231710">
        <addColumn tableName="programming_exercise_test_case">
            <column name="bonus_multiplier" type="DOUBLE" defaultValue="1.0"/>
            <column name="bonus_points" type="DOUBLE" defaultValue="0.0"/>
        </addColumn>
        <modifyDataType tableName="programming_exercise_test_case" columnName="weight" newDataType="DOUBLE"/>
        <addDefaultValue tableName="programming_exercise_test_case" columnName="weight" defaultValue="1.0"/>
        <addColumn tableName="exercise">
            <column name="bonus_points" type="DOUBLE" defaultValue="0.0"/>
        </addColumn>
    </changeSet>
</databaseChangeLog>
```

**Comment by schultek** [comment]
See how a NaN value in the weight column gets converted to null, but a NaN value in the bonusMultiplier column gets converted to the default value of 1.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/13920539/99525755-8a7bbe80-299a-11eb-8268-4228c0eefa25.gif)

**Comment by krusche** [comment]
I think the reason is that weight does not have a default value in the database. 
This means we need two fixes:
1) A default value '1' for the weight column
2) Prevent the client from sending null values. Instead use the default value. In case the user does not specify the value and leaves the focus of the textfield, the default value should automatically be inserted

**Comment by schultek** [comment]
Wasn't the default value for the weight column added in the liquibase changelog above?

**Comment by krusche** [comment]
You are right, I overlooked this. Then this case should basically never happen and there might be another reason.
I just checked the database and there are no null values.
We should still prevent that the client sends NaN or null values to the server

**Comment by schultek** [comment]
Okay, then it must be something else.
Basically what is happening is that in the credits calculation for the automated feedbacks (either testcase or sca) something must be null which results in the whole calculation being NaN. 
I found the same error in sentry occurring for the new-result endpoint as well as the re-evaluate endpoint, both of which use the updateScore method in the ProgrammingExerciseGradingService.

**Comment by schultek** [comment]
I will fix the null issue on the client side, however this will just fix the issue for new or updated exercises.

**Comment by kloessst** [comment]
I would also add a check to the update test cases request which checks for null and NaN and returns a 400 then.
