### ISSUE TITLE
createManualProgrammingExerciseResult_resultExists fails on develop

### ISSUE THREAD

**Issue by iozbeyli** [ls1intum/Artemis#2495]
There is a failing test on develop branch.

ProgrammingAssessmentIntegrationTest > createManualProgrammingExerciseResult_resultExists() FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting value to be true but was false
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at de.tum.in.www1.artemis.programmingexercise.ProgrammingAssessmentIntegrationTest.createManualProgrammingExerciseResult_resultExists(ProgrammingAssessmentIntegrationTest.java:370)

**Comment by anditurdiu** [comment]
Maybe this is a flaky test? the latest build on bamboo shows all tests passing client + server: 
https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS-1680

**Comment by iozbeyli** [comment]
It might be fixed after I opened this issue.
