### ISSUE TITLE
Can not delete test run if test run has one exercise that has no participation

### ISSUE THREAD

**Issue by 1-alex98** [ls1intum/Artemis#2986]
#### To Reproduce

1. Craete a test run
2. Leave an exercise without a participation
3. Try to delte it

Probably:
```
testRun.getExercises().forEach(exercise -> {
    final StudentParticipation relevantParticipation = exercise.findRelevantParticipation(participations);
    exercise.setStudentParticipations(relevantParticipation == null? Set.of() : Set.of(relevantParticipation));
});
```
would fix it in StudentExamService::deleteTestRun 

Exception:

```
artemis                    | 2021-03-08 13:30:17.957 ERROR 1 --- [o-8080-exec-271] o.z.problem.spring.common.AdviceTraits   : Internal Server Error
artemis                    |
artemis                    | java.lang.NullPointerException: null
artemis                    |    at java.base/java.util.Objects.requireNonNull(Objects.java:208)
artemis                    |    at java.base/java.util.ImmutableCollections$Set12.<init>(ImmutableCollections.java:620)
artemis                    |    at java.base/java.util.Set.of(Set.java:468)
artemis                    |    at de.tum.in.www1.artemis.service.exam.StudentExamService.lambda$deleteTestRun$17(StudentExamService.java:549)
artemis                    |    at java.base/java.lang.Iterable.forEach(Iterable.java:75)
artemis                    |    at de.tum.in.www1.artemis.service.exam.StudentExamService.deleteTestRun(StudentExamService.java:549)
artemis                    |    at de.tum.in.www1.artemis.web.rest.StudentExamResource.assessUnsubmittedStudentExamsAndEmptySubmissions(StudentExamResource.java:410)
artemis                    |    at de.tum.in.www1.artemis.web.rest.StudentExamResource$$FastClassBySpringCGLIB$$12ee3abb.invoke(<generated>)
artemis                    |    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
artemis                    |    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
artemis                    |    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
artemis                    |    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
artemis                    |    at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:61)
artemis                    |    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
artemis                    |    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
artemis                    |    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
artemis                    |    at de.tum.in.www1.artemis.web.rest.StudentExamResource$$EnhancerBySpringCGLIB$$cbdefd9.assessUnsubmittedStudentExamsAndEmptySubmissions($
generated>)
artemis                    |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
artemis                    |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
artemis                    |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
artemis                    |    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
artemis                    |    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
artemis                    |    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
artemis                    |    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.jav$
:106)
artemis                    |    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.j$
va:894)
artemis                    |    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:8$
8)
artemis                    |    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
artemis                    |    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
artemis                    |    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
artemis                    |    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
artemis                    |    at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
artemis                    |    at javax.servlet.http.HttpServlet.service(HttpServlet.java:523)
artemis                    |    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
artemis                    |    at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
artemis                    |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
artemis                    |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
artemis                    |    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
artemis                    |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
artemis                    |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
artemis                    |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:113)
artemis                    |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
artemis                    |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
artemis                    |    at de.tum.in.www1.artemis.config.ApiVersionFilter.doFilter(ApiVersionFilter.java:46)
artemis                    |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
artemis                    |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
artemis                    |    at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:67)
artemis                    |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
artemis                    |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
artemis                    |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
artemis                    |    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
artemis                    |    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
```

**Comment by 1-alex98** [comment]
Really want to but don't find the time :(

**Comment by krusche** [comment]
I busted looked into the code and this was already implemented and integrated on February 23
<img width="981" alt="image" src="https://user-images.githubusercontent.com/744067/111217687-2084c600-85d6-11eb-9f35-87cbe362515a.png">

You are running on outdated code. Please update to the latest version before you create issues.
Also, when you create issues, please mention which Artemis version you are running, otherwise it's really hard to tell whether the issue was already resolved of not.

**Comment by 1-alex98** [comment]
Yes we will update

**Comment by 1-alex98** [comment]
But it was risky before the exam
