### ISSUE TITLE
`Programming Tasks`: Malformed input or input contains unmappable characters

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#4439]
### Describe the bug

Artemis cannot load Tasks from GitLab if the Path contains characters like: äöü.

GitLab contains:
![image](https://user-images.githubusercontent.com/22198798/144573869-1eb4894a-7a30-4ff7-a778-21fb269275d9.png)

And Artemis encounters an internal server error while loading the repository:
```
Caused by: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /opt/Artemis/data/repos-download/1638521186302/PROGRAMMING2122SHEET2TASKA/programming2122sheet2taska-XYZABC/._Übungsblatt_02.iml8367470496992632905.tmp
        at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:145)
        at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
        at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:276)
        at java.base/java.io.File.toPath(File.java:2353)
        at org.eclipse.jgit.util.FileUtils.isFile(FileUtils.java:802)
        at org.eclipse.jgit.util.FileUtils.canExecute(FileUtils.java:831)
        at org.eclipse.jgit.util.FS_POSIX.canExecute(FS_POSIX.java:205)
        at org.eclipse.jgit.dircache.DirCacheCheckout.checkoutEntry(DirCacheCheckout.java:1506)
        at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:563)
        at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:467)
        at org.eclipse.jgit.api.CloneCommand.checkout(CloneCommand.java:385)
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:212)
        at de.tum.in.www1.artemis.service.connectors.GitService.getOrCheckoutRepository(GitService.java:444)

```

### To Reproduce

1. Create a Programming Task
2. Create a commit with a file name that contains ÄÖÜ
3. Try to open the Repo in Artemis

### Expected behavior

The Repository shall be displayed / no error is expected. Or at least a hint in the Artemis Frontend that the user shall edit their latest Git commit that it might be loadable.

### What browsers are you seeing the problem on?

Firefox

**Comment by Shirkanesi** [comment]
Related (duplicate) to #4432, however this issue is slightly more detailed.

**Comment by krusche** [comment]
Do you consistently use UTF-8 on the servers?

**Comment by dfuchss** [comment]
The UTF-8 hint was helpful. I've found out that the default docker image uses C.UTF-8 but our systems using en_US.UTF-8.
You may consider to add this to your Dockerfiles as well.
Currently, I'm testing whether changing the locale resolves the issues with the file system.

**Comment by dfuchss** [comment]
Thanks for the hint @krusche . The locale was the problem. As mentioned above, this could be added to your Dockerfiles & Documentation :)

https://github.com/kit-sdq/Artemis4Docker/commit/d77ca6f91fab9266ba45c86941b0cbca7b68eb79

**Comment by krusche** [comment]
Great that you could resolve it. Could you add a hint to the docker file in a PR? Or even better: could we integrate the correct locale settings into the dockerfile? Maybe a custom built docker image?
