### ISSUE TITLE
Nullpointer Exception while Trigger All

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#4463]
### Describe the bug

We had to trigger all build plans, since we've updates some test cases.

I've marked it as high, since we need this feature if we have to adapt some test cases due to student responses.

What happened:
* Not all Builds have been triggered 
* Got this exception in the BE

```
2021-12-07 10:07:22.610 ERROR 12 --- [ artemis-task-1] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void de.tum.in.www1.artemis.service.programming.ProgrammingSubmissionService.triggerInstructorBuildForExercise(java.lang.Long) throws de.tum.in.www1.artemis.web.rest.errors.EntityNotFoundException

java.lang.NullPointerException: Cannot invoke "org.eclipse.jgit.lib.ObjectId.getName()" because the return value of "de.tum.in.www1.artemis.service.connectors.GitService.getLastCommitHash(de.tum.in.www1.artemis.domain.VcsRepositoryUrl)" is null
        at de.tum.in.www1.artemis.service.programming.ProgrammingSubmissionService.getLastCommitHashForParticipation(ProgrammingSubmissionService.java:368)
        at de.tum.in.www1.artemis.service.programming.ProgrammingSubmissionService.getOrCreateSubmissionWithLastCommitHashForParticipation(ProgrammingSubmissionService.java:359)
        at de.tum.in.www1.artemis.service.programming.ProgrammingSubmissionService.triggerBuildAndNotifyUser(ProgrammingSubmissionService.java:429)
        at de.tum.in.www1.artemis.service.programming.ProgrammingSubmissionService.triggerBuildForParticipations(ProgrammingSubmissionService.java:316)
        at de.tum.in.www1.artemis.service.programming.ProgrammingSubmissionService.triggerInstructorBuildForExercise(ProgrammingSubmissionService.java:291)
        at de.tum.in.www1.artemis.service.programming.ProgrammingSubmissionService$$FastClassBySpringCGLIB$$fadb5611.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at tech.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

### To Reproduce

1. Trigger All for a Programming Task (Unclear what the internal state of all participations must be)

### Expected behavior

Trigger all should not fail. And should trigger all participations.

### What browsers are you seeing the problem on?

Firefox

**Comment by dfuchss** [comment]
I assume that the possibility that `gitService.getLastCommitHash(programmingExercise.getVcsTestRepositoryUrl())` can return `null` was not considered when writing `return gitService.getLastCommitHash(programmingExercise.getVcsTestRepositoryUrl()).getName()` :)

**Comment by krusche** [comment]
I think the whole method needs to change, there is no need to retrieve the last commit hash from git to trigger the builds. The whole method should work with the participation and **not** with the submission.

I started to work on this issue in the branch `bugfix/improve-trigger-all`, but this is only a raw draft
