### ISSUE TITLE
Uncaught exception in Artemis Client when deleting an exercise

### ISSUE THREAD

**Issue by jhainzlschmid** [ls1intum/Artemis#4654]
### Describe the bug

When deleting an exercise the Artemis Client throws an uncaught exception (TypeError). The deletion still works, but the Cypress tests testing the deletion fail because the client throws an uncaught exception. I manually tested this with an text exercise, but the Cypress test results suggest that the same exception is also thrown for quiz and programming exercises.

### To Reproduce

1. Go to course management and create a new course
2. Create a new text exercise in the new course
3. Delete the exercise again
4. See error in the console in the developer tools

### Expected behavior

I shouldn't see any error in the console when following the steps mentioned above

### Screenshots

![image](https://user-images.githubusercontent.com/12861668/151697680-6b3327a7-aeb8-4fa7-9698-19ac81cfad7e.png)

### What browsers are you seeing the problem on?

Chrome

### Additional context

I only tested on chrome. The cypress tests are also running on chrome.

### Relevant log output

```shell
zone.js:182 Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at d.handleError (sentry.error-handler.ts:45:19)
    at Object.next (core.mjs:26052:42)
    at Object.next (Subscriber.js:110:13)
    at H._next (Subscriber.js:60:26)
    at H.next (Subscriber.js:31:18)
    at Subject.js:31:30
    at t (errorContext.js:19:9)
    at Vp.next (Subject.js:26:9)
    at Vp.emit (core.mjs:22430:15)
    at core.mjs:25524:55
    at T.invoke (zone.js:372:26)
    at M.run (zone.js:134:43)
    at rc.runOutsideAngular (core.mjs:25397:28)
    at Object.onHandleError (core.mjs:25524:18)
    at T.handleError (zone.js:376:37)
    at M.runTask (zone.js:181:44)
    at invokeTask (zone.js:487:34)
    at invoke (zone.js:476:48)
    at m.args.<computed> (zone.js:2541:32)
```

**Comment by krusche** [comment]
should be fixed now
