### ISSUE TITLE
Duplicate DB entries for latest participant score leads to no new results being created

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#5014]
### Describe the bug

There can be cases where in the table `participant_score` exist two entries for the same `user_id` and `exercise_id`. Therefore, the query `findStudentScoreByExerciseAndUser` assuming uniqueness on a combination of those two values no longer works and no new results are created as the query checking for existing ones fails and aborts the save.

### To Reproduce

No real consistent reproduction, noticed for five students so far.

### Expected behavior

There should only ever be one unique entry for a `user_id`,`exercise_id` combination in the table `participant_score`.

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

- Artemis 5.7.5
- MySQL 8.0.28

### Relevant log output

```shell
2022-05-03 19:27:45.764  INFO 18940 --- [1-8080-exec-148] d.t.i.w.artemis.web.rest.ResultResource  : Artemis received a new result for build plan <OMITTED>
2022-05-03 19:27:45.947 ERROR 18940 --- [1-8080-exec-148] o.z.problem.spring.common.AdviceTraits   : Internal Server Error
org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:571)
        […]
        at jdk.proxy2/jdk.proxy2.$Proxy280.save(Unknown Source)
        at de.tum.in.www1.artemis.service.programming.ProgrammingExerciseGradingService.processNewProgrammingExerciseResult(ProgrammingExerciseGradingService.java:280)
        at de.tum.in.www1.artemis.service.programming.ProgrammingExerciseGradingService.lambda$processNewProgrammingExerciseResult$1(ProgrammingExerciseGradingService.java:166)
        at java.base/java.util.Optional.map(Optional.java:260)
        at de.tum.in.www1.artemis.service.programming.ProgrammingExerciseGradingService.processNewProgrammingExerciseResult(ProgrammingExerciseGradingService.java:166)
        at de.tum.in.www1.artemis.web.rest.ResultResource.notifyNewProgrammingExerciseResult(ResultResource.java:176)
        at de.tum.in.www1.artemis.web.rest.ResultResource$$FastClassBySpringCGLIB$$86afbfd8.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at de.tum.in.www1.artemis.web.rest.ResultResource$$EnhancerBySpringCGLIB$$a42ded04.notifyNewProgrammingExerciseResult(<generated>)
        at jdk.internal.reflect.GeneratedMethodAccessor814.invoke(Unknown Source)
        […]
Caused by: javax.persistence.RollbackException: Error while committing the transaction
        at org.hibernate.internal.ExceptionConverterImpl.convertCommitException(ExceptionConverterImpl.java:81)
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:104)
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:562)
        ... 95 common frames omitted
Caused by: org.springframework.dao.IncorrectResultSizeDataAccessException: query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2
        at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:385)
        […]
        at jdk.proxy2/jdk.proxy2.$Proxy345.findStudentScoreByExerciseAndUser(Unknown Source)
        at de.tum.in.www1.artemis.service.ScoreService.getExistingParticipationScore(ScoreService.java:192)
        at de.tum.in.www1.artemis.service.ScoreService.updateOrCreateParticipantScore(ScoreService.java:145)
        at de.tum.in.www1.artemis.service.ScoreService$$FastClassBySpringCGLIB$$2ab18cef.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        […]
        at de.tum.in.www1.artemis.service.ScoreService$$EnhancerBySpringCGLIB$$3b4d7f47.updateOrCreateParticipantScore(<generated>)
        at de.tum.in.www1.artemis.service.ScoreService$$FastClassBySpringCGLIB$$2ab18cef.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at de.tum.in.www1.artemis.service.ScoreService$$EnhancerBySpringCGLIB$$981069de.updateOrCreateParticipantScore(<generated>)
        at de.tum.in.www1.artemis.service.listeners.ResultListener.updateOrCreateParticipantScore(ResultListener.java:59)
        at jdk.internal.reflect.GeneratedMethodAccessor804.invoke(Unknown Source)
        […]
        ... 96 common frames omitted
Caused by: javax.persistence.NonUniqueResultException: query did not return a unique result: 2
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:128)
        […]
        ... 151 common frames omitted
```

**Comment by dfuchss** [comment]
Occurred for us as well during exams.

**Comment by b-fein** [comment]
The DB does not enforce the uniqueness, instead that happens in the server logic:

- In https://github.com/ls1intum/Artemis/blob/98b540c1d8a15c049a7426aee7b57b588ef8fe1d/src/main/java/de/tum/in/www1/artemis/service/ScoreService.java#L144 it is checked if one exists, and then either an existing one is updated or a new one will be created.
- However, in between running through the logic from here to the save point, other results for the same exercise can be received from the CI system. In that case the score still does not exist in the DB, `createNewStudentScore` is called for this result, too, and then both calls to save are executed, therefore resulting in the non-unique entries.
