### ISSUE TITLE
Git Exception: Nothing to fetch

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#5476]
### Describe the bug

Sometimes students repositories cannot be fetched from artemis.

```
2022-07-26 12:32:36.928 ERROR 1 --- [o-8080-exec-122] o.z.problem.spring.common.AdviceTraits   : Internal Server Error

org.eclipse.jgit.api.errors.TransportException: Nothing to fetch.
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:224)
        at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:266)
        at de.tum.in.www1.artemis.service.connectors.GitService.pull(GitService.java:784)
        at de.tum.in.www1.artemis.service.connectors.GitService.getOrCheckoutRepository(GitService.java:423)
        at de.tum.in.www1.artemis.service.connectors.GitService.getOrCheckoutRepository(GitService.java:397)
        at de.tum.in.www1.artemis.service.connectors.GitService.getOrCheckoutRepository(GitService.java:380)
        at de.tum.in.www1.artemis.service.connectors.GitService.getOrCheckoutRepository(GitService.java:355)
        at de.tum.in.www1.artemis.service.connectors.GitService.getOrCheckoutRepository(GitService.java:340)
        at de.tum.in.www1.artemis.service.connectors.GitService$$FastClassBySpringCGLIB$$ddf6183f.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at de.tum.in.www1.artemis.service.connectors.GitService$$EnhancerBySpringCGLIB$$b14d6cca.getOrCheckoutRepository(<generated>)
        at de.tum.in.www1.artemis.service.RepositoryService.isClean(RepositoryService.java:298)
        at de.tum.in.www1.artemis.web.rest.repository.RepositoryResource.getStatus(RepositoryResource.java:291)
        at de.tum.in.www1.artemis.web.rest.repository.RepositoryProgrammingExerciseParticipationResource.getStatus(RepositoryProgrammingExerciseParticipationResource.java:373)
        at de.tum.in.www1.artemis.web.rest.repository.RepositoryProgrammingExerciseParticipationResource$$FastClassBySpringCGLIB$$9ebf5bf.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:61)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at de.tum.in.www1.artemis.web.rest.repository.RepositoryProgrammingExerciseParticipationResource$$EnhancerBySpringCGLIB$$3117670d.getStatus(<generated>)
        at jdk.internal.reflect.GeneratedMethodAccessor862.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

### To Reproduce

Unknown

### Expected behavior

Artemis shall handle the exception. E.g., reclone the repository or clear caches ?

### What browsers are you seeing the problem on?

Firefox

**Comment by dfuchss** [comment]
It seems that .git/config is incomplete:

```
root@i43vm-program /s/a/d/a/d/r/S/swt1sose22uiconnection-uxxxx# cat .git/config                                                                                                                   main
[gc]
        auto = 0
[core]
        symlinks = false
[branch "main"]
        remote = origin
        merge = refs/heads/main
```

**Comment by dfuchss** [comment]
To resolve the issue, you have to delete the repository (local file system of artemis) in order to recreate the files.
