### ISSUE TITLE
`Programming exercises`: Checking plagiarism fails

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#5945]
### Describe the bug

Checking for plagiarism in programming exercises fails. See log below.

### To Reproduce

1. Use a Java programming exercise with multiple submissions.
2. Use the Check Plagiarism > Detect plagiarism functionality.
3. The InternalServerError as below appears.

### Expected behavior

The plagiarism result is created without error.

### Which version of Artemis are you seeing the problem on?

5.12.6

### What browsers are you seeing the problem on?

Firefox

### Additional context

cc @dfuchss: You might know if this is specific to how JPlag is used as a dependency in Artemis, or if this happens with standalone JPlag, too.

### Relevant log output

```shell
Caused by: java.lang.NoClassDefFoundError: com/sun/source/tree/TreeVisitor
        at de.jplag.java.Parser.parse(Parser.java:25)
        at de.jplag.java.Language.parse(Language.java:47)
        at de.jplag.Submission.parse(Submission.java:249)
        at de.jplag.SubmissionSet.parseSubmissions(SubmissionSet.java:147)
        at de.jplag.SubmissionSet.parseAllSubmissions(SubmissionSet.java:103)
        at de.jplag.SubmissionSet.<init>(SubmissionSet.java:45)
        at de.jplag.SubmissionSetBuilder.buildSubmissionSet(SubmissionSetBuilder.java:78)
        at de.jplag.JPlag.run(JPlag.java:43)
        at de.tum.in.www1.artemis.service.plagiarism.ProgrammingPlagiarismDetectionService.computeJPlagResult(ProgrammingPlagiarismDetectionService.java:206)
```

**Comment by dfuchss** [comment]
CC @tsaglam :)

**Comment by tsaglam** [comment]
@dfuchss @b-fein, we at JPlag are not aware of this issue yet. One way to check this would be by running standalone JPlag for the submissions in Artemis (download them and run JPlag locally). The exception suggests a class loader problem. However, seems that is wraps another exception, which is not included in the log above.

**Comment by b-fein** [comment]
I can reproduce it by loading the JPlag JAR from your official release into the Artemis container and running it:
```bash
docker run --rm -it -v $(pwd):/jplag_data --entrypoint /bin/bash ghcr.io/ls1intum/artemis:5.12.6
```
```
root@b7ea47b9422a:/jplag_data# java -jar jplag-4.1.0-jar-with-dependencies.jar submissions/
2022-12-12-04:01:46_569 [main] [INFO] LanguageLoader - Available languages: '[C/C++ Scanner [basic markup], C# 6 Parser, EMF metamodel, Go Parser, Javac based AST plugin, Kotlin Parser, Python3 Parser, R Parser, Rust Language Module, Scala parser, SchemeR4RS Parser [basic markup], Swift Parser, Text Parser (naive)]'
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/source/tree/TreeVisitor
        at de.jplag.java.Parser.parse(Parser.java:25)
        at de.jplag.java.Language.parse(Language.java:47)
        at de.jplag.Submission.parse(Submission.java:249)
        at de.jplag.SubmissionSet.parseSubmissions(SubmissionSet.java:147)
        at de.jplag.SubmissionSet.parseAllSubmissions(SubmissionSet.java:103)
        at de.jplag.SubmissionSet.<init>(SubmissionSet.java:45)
        at de.jplag.SubmissionSetBuilder.buildSubmissionSet(SubmissionSetBuilder.java:78)
        at de.jplag.JPlag.run(JPlag.java:43)
        at de.jplag.cli.CLI.main(CLI.java:90)
Caused by: java.lang.ClassNotFoundException: com.sun.source.tree.TreeVisitor
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 9 more
```

Might that be because the container only contains the JRE and the missing class is only part of the full JDK?
```Dockerfile
FROM eclipse-temurin:17-jre
```
```
root@b7ea47b9422a:/jplag_data# java --version
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)
```

**Comment by dfuchss** [comment]
Sounds reasonable. I guess the change to jre caused this problem :) https://github.com/ls1intum/Artemis/pull/5739.
