### ISSUE TITLE
Broken breadcrumb link in text assessment view

### ISSUE THREAD

**Issue by pal03377** [ls1intum/Artemis#6778]
### Describe the bug

A console error appears when clicking on the "Submissions" part in the breadcrumbs on the top in the text assessment view.

### To Reproduce

1. Go to the exercise dashboard of any text exercise with existing submissions (as tutor or higher)
2. Go to the assessment view
3. Click on the "Submissions" link on the top (see screenshot)
4. See error message appear in the DevTools console in Chrome.

### Expected behavior

No error appears.

### Screenshots

![screenshot-2023-06-27_001472](https://github.com/ls1intum/Artemis/assets/9006596/cb296f7a-bc50-45e6-b3c3-653e41d1c8d1)

### Which version of Artemis are you seeing the problem on?

6.3.2

### What browsers are you seeing the problem on?

Chrome

### Additional context

The error from the logs hints at a missing child route. Probably, the "submissions" part should not be a link at all.

### Relevant log output

```shell
ERROR Error: Uncaught (in promise): Error: NG04002
Error: NG04002
    at ln.noMatchError (router.mjs:3655:16)
    at router.mjs:3670:28
    at catchError.js:10:39
    at t._error (OperatorSubscriber.js:23:21)
    at t.error (Subscriber.js:40:18)
    at t._error (Subscriber.js:64:30)
    at t.error (Subscriber.js:40:18)
    at t._error (Subscriber.js:64:30)
    at t.error (Subscriber.js:40:18)
    at t._error (Subscriber.js:64:30)
    at t.error (Subscriber.js:40:18)
    at t._error (Subscriber.js:64:30)
    at t.error (Subscriber.js:40:18)
    at t._error (Subscriber.js:64:30)
    at t.error (Subscriber.js:40:18)
    at t._error (Subscriber.js:64:30)
    at t.error (Subscriber.js:40:18)
    at T.C [as _subscribe] (throwError.js:5:45)
    at T._trySubscribe (Observable.js:37:25)
    at Observable.js:31:30
    at t (errorContext.js:19:9)
    at T.subscribe (Observable.js:22:9)
    at catchError.js:23:27
    at t.<anonymous> (lift.js:10:28)
    at Observable.js:26:30
    at t (errorContext.js:19:9)
    at T.subscribe (Observable.js:22:9)
    at W (mergeInternals.js:19:44)
    at H (mergeInternals.js:14:57)
    at t._next (OperatorSubscriber.js:13:21)
    at t.next (Subscriber.js:31:18)
    at T._subscribe (innerFrom.js:51:24)
    at T._trySubscribe (Observable.js:37:25)
    at Observable.js:31:30
    at t (errorContext.js:19:9)
    at T.subscribe (Observable.js:22:9)
    at u (mergeInternals.js:50:12)
    at mergeMap.js:13:44
    at t.<anonymous> (lift.js:10:28)
    at Observable.js:26:30
    at t (errorContext.js:19:9)
    at T.subscribe (Observable.js:22:9)
    at scanInternals.js:7:16
    at t.<anonymous> (lift.js:10:28)
    at Observable.js:26:30
    at t (errorContext.js:19:9)
    at T.subscribe (Observable.js:22:9)
    at defaultIfEmpty.js:6:16
    at t.<anonymous> (lift.js:10:28)
    at Observable.js:26:30
    at Q (zone.js:1193:31)
    at Q (zone.js:1147:17)
    at zone.js:1260:17
    at _.invokeTask (zone.js:402:31)
    at Object.onInvokeTask (core.mjs:26236:33)
    at _.invokeTask (zone.js:401:60)
    at j.runTask (zone.js:171:47)
    at p (zone.js:581:35)
    at E.invokeTask [as invoke] (zone.js:487:21)
    at O (zone.js:1631:18)
    at I (zone.js:1674:33)
    at HTMLAnchorElement.M (zone.js:1695:16)
```

**Comment by b-fein** [comment]
Possibly related to changes from #6677
