### ISSUE TITLE
Download of Exercise does not work

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#6935]
### Describe the bug

If I click on Download Exercise for a Programming Task, I get an internal Server Error in Browser Logs.

### To Reproduce

1. Go to a programming task (course mgmt)
2. Click on Download Exercise
3. See error in the log of the browser

### Expected behavior

Download options shall be shown

### Which version of Artemis are you seeing the problem on?

6.3.3

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
ERROR 
Object { headers: {…}, status: 500, statusText: "Internal Server Error", url: "https://artemis.praktomat.cs.kit.edu/api/programming-exercises/172/export-instructor-exercise", ok: false, name: "HttpErrorResponse", message: "Http failure response for https://artemis.praktomat.cs.kit.edu/api/programming-exercises/172/export-instructor-exercise: 500 Internal Server Error", error: Blob }
​
error: Blob { size: 273, type: "application/problem+json", … }
​
headers: Object { normalizedNames: Map(0), lazyUpdate: null, lazyInit: lazyInit() }
​
message: "Http failure response for https://artemis.praktomat.cs.kit.edu/api/programming-exercises/172/export-instructor-exercise: 500 Internal Server Error"
​
name: "HttpErrorResponse"
​
ok: false
​
status: 500
​
statusText: "Internal Server Error"
​
url: "https://artemis.praktomat.cs.kit.edu/api/programming-exercises/172/export-instructor-exercise"
​
<prototype>: Object { … }
core.mjs:10183:22

```
```

**Comment by dfuchss** [comment]
If I access the API endpoint in the browser:
![image](https://github.com/ls1intum/Artemis/assets/22198798/a675da02-90ae-4491-baaf-f8be0d269bf4)

**Comment by tobias-lippert** [comment]
Hi @dfuchss, the only way I could reproduce this was by setting the problem statement to null in the database. Could you check in the database if this is the case here?
I also checked that we do not set the problem statement to null in the database if we create an exercise with an empty problem statement.

**Comment by krusche** [comment]
@tobias-lippert thanks for looking into this. Could you make sure the export also works in case any property in the programming exercise is null?

**Comment by dfuchss** [comment]
The exception on the server side is:
```
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
        at java.base/java.io.Writer.write(Writer.java:249)
        at de.tum.in.www1.artemis.service.FileService.writeStringToFile(FileService.java:1077)
        at de.tum.in.www1.artemis.service.FileService$$FastClassBySpringCGLIB$$24249aed.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
        at de.tum.in.www1.artemis.service.FileService$$EnhancerBySpringCGLIB$$b9697432.writeStringToFile(<generated>)
        at de.tum.in.www1.artemis.service.programming.ProgrammingExerciseExportService.exportProgrammingExerciseInstructorMaterial(ProgrammingExerciseExportService.java:131)
        at de.tum.in.www1.artemis.web.rest.ProgrammingExerciseExportImportResource.exportInstructorExercise(ProgrammingExerciseExportImportResource.java:269)
        at de.tum.in.www1.artemis.web.rest.ProgrammingExerciseExportImportResource$$FastClassBySpringCGLIB$$12ce872b.invoke(<generated>) 
        ...
```

Database: Yes, the statement is NULL.
```
exercise
+-----+---------------------+-------------------------+-------------------------+-----------+------------------------------------------------+---------------+----------+--------------------------------------------+------------------------------------------+--------------------------------------------------+----------------------------+----------------------------------------------------+-------------------------+------------+--------------+------------+------------+--------------+----------------------+-------------------+------------------+------------------------------+------------------------+-------------+----------------------------------------------------------------------------------------------+----------------+----------------------+-------------------------+---------------------------+---------------------------+--------------------------------------------+-----------------+--------------------------------------------------------+---------------------------+-------------------+--------------+---------------------------+------------------------------------------------------+----------------------------------------------------------------------------------------+----------------------+-----------------------------------+--------------+-------------------------------+----------------------------------------------------------------+-------------------------+---------------+
| id  | title               | release_date            | due_date                | course_id | publish_build_plan_url                         | discriminator | duration | is_open_for_practice                       | is_planned_to_start                      | is_visible_before_start                          | allowed_number_of_attempts | randomize_question_order                           | quiz_point_statistic_id | max_points | diagram_type | difficulty | mode       | file_pattern | grading_instructions | problem_statement | example_solution | example_solution_explanation | example_solution_model | short_name  | test_repository_url                                                                          | package_name   | programming_language | assessment_due_date     | solution_participation_id | template_participation_id | sequential_test_runs                       | assessment_type | presentation_score_enabled                             | team_assignment_config_id | exercise_group_id | bonus_points | included_in_overall_score | second_correction_enabled                            | allow_complaints_for_automatic_assessments                                             | submission_policy_id | example_solution_publication_date | quiz_mode    | allowed_per_tutor_batch_count | allow_manual_feedback_requests                                 | start_date              | build_plan_id |
+-----+---------------------+-------------------------+-------------------------+-----------+------------------------------------------------+---------------+----------+--------------------------------------------+------------------------------------------+--------------------------------------------------+----------------------------+----------------------------------------------------+-------------------------+------------+--------------+------------+------------+--------------+----------------------+-------------------+------------------+------------------------------+------------------------+-------------+----------------------------------------------------------------------------------------------+----------------+----------------------+-------------------------+---------------------------+---------------------------+--------------------------------------------+-----------------+--------------------------------------------------------+---------------------------+-------------------+--------------+---------------------------+------------------------------------------------------+----------------------------------------------------------------------------------------+----------------------+-----------------------------------+--------------+-------------------------------+----------------------------------------------------------------+-------------------------+---------------+
| 172 | Blatt 5 - Aufgabe A | 2023-06-20 10:00:00.000 | 2023-07-06 04:00:00.000 |        18 | 0x00                                           | P             |     NULL | NULL                                       | NULL                                     | NULL                                             |                       NULL | NULL                                               |                    NULL |         20 | NULL         | NULL       | INDIVIDUAL | NULL         | NULL                 | NULL              | NULL             | NULL                         | NULL                   | Sheet5TaskA | https://git.praktomat.cs.kit.edu/PROGRAMMING23SHEET5TASKA/programming23sheet5taska-tests.git | edu.kit.kastel | JAVA                 | 2023-07-13 15:00:00.000 |                     42789 |                     42788 | 0x00                                       | SEMI_AUTOMATIC  | 0x00                                                   |                      NULL |              NULL |            0 | INCLUDED_COMPLETELY       | 0x00                                                 | 0x00                                                                                   |                 NULL | 2023-07-06 16:00:00.000           | SYNCHRONIZED |                          NULL | 0x00                                                           | 2023-06-28 10:00:00.000 |          NULL |
+-----+---------------------+-------------------------+-------------------------+-----------+------------------------------------------------+---------------+----------+--------------------------------------------+------------------------------------------+--------------------------------------------------+----------------------------+----------------------------------------------------+-------------------------+------------+--------------+------------+------------+--------------+----------------------+-------------------+------------------+------------------------------+------------------------+-------------+----------------------------------------------------------------------------------------------+----------------+----------------------+-------------------------+---------------------------+---------------------------+--------------------------------------------+-----------------+--------------------------------------------------------+---------------------------+-------------------+--------------+---------------------------+------------------------------------------------------+----------------------------------------------------------------------------------------+----------------------+-----------------------------------+--------------+-------------------------------+----------------------------------------------------------------+-------------------------+---------------+

```
