### ISSUE TITLE
Courses cannot be deleted

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#7735]
### Describe the bug

Since we have to clean up our courses regularly, I was about about to delete some old courses. 

Unfortunately, the courses cannot be deleted because of the following exception:

```
java.lang.NullPointerException: Cannot invoke "de.tum.in.www1.artemis.domain.Result.setParticipation(de.tum.in.www1.artemis.domain.participation.Participation)" because "result" is null
        at de.tum.in.www1.artemis.domain.participation.Participation.removeResult(Participation.java:182)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at de.tum.in.www1.artemis.service.ParticipationService.deleteResultsAndSubmissionsOfParticipation(ParticipationService.java:770)
        at de.tum.in.www1.artemis.service.ParticipationService.delete(ParticipationService.java:743)
        at de.tum.in.www1.artemis.service.ParticipationService.deleteAllByExerciseId(ParticipationService.java:800)
        at de.tum.in.www1.artemis.service.ExerciseDeletionService.delete(ExerciseDeletionService.java:158)
        at de.tum.in.www1.artemis.web.rest.ProgrammingExerciseResource.deleteProgrammingExercise(ProgrammingExerciseResource.java:483)
        at de.tum.in.www1.artemis.web.rest.ProgrammingExerciseResource$$FastClassBySpringCGLIB$$2872f592.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
```

### To Reproduce

Try to delete courses on a production system

### Expected behavior

Courses should be deleted without error.

### Which version of Artemis are you seeing the problem on?

6.7.0

### What browsers are you seeing the problem on?

Firefox

**Comment by dfuchss** [comment]
I've resolved the current issues with manual sql queries in the db
