### ISSUE TITLE
Programming-Exercises: Saving in "edit in editor" broken

### ISSUE THREAD

**Issue by thilo-behnke** [ls1intum/Artemis#788]
### Describe the bug

**Cause:**

Regression from https://github.com/ls1intum/Artemis/pull/757.
A standard jpa method was changed to a custom method with an explicit query. When an explicit query is used, the authentication object has to be available in the SecurityContext, otherwise the method fails (known bug: https://jira.spring.io/browse/DATAJPA-1357).

In the mentioned PR the method `UserRepository.findOneWithGroupsAndAuthoritiesByLogin` was changed to a custom jpa method.
Now websocket channel endpoints that use this method, will fail with the following error: 
`java.lang.IllegalArgumentException: Authentication object cannot be null`

This is not a security issue afaik as Spring Boot takes care of the websocket authorization, but it will not create the authentication object in the SecurityContext.

There are 3 ways to fix this:
1. Hotfix: Don't use custom jpa methods in websocket channels (this is probably not feasible as the regression shows)
2. Hotfix: In every `@MessageMapping` use the `SecuritUtils.setAuthorizationObject` method to set a dummy object. The problem is that we might forget to do this.
3. Proper solution but probably over-engineered: Create a custom authorization handler for websocket messages (https://stackoverflow.com/questions/45405332/websocket-authentication-and-authorization-in-spring)

**Effect:**

#/code-editor/797/admin/140962

Saving a file is not working because of a server error while processing the websocket message:

```
at de.tum.in.www1.artemis.service.UserService$$EnhancerBySpringCGLIB$$c7f7080e.getUserWithGroupsAndAuthorities(<generated>)
	at de.tum.in.www1.artemis.service.ProgrammingExerciseParticipationService.canAccessParticipation(ProgrammingExerciseParticipationService.java:156)
	at de.tum.in.www1.artemis.service.ProgrammingExerciseParticipationService.canAccessParticipation(ProgrammingExerciseParticipationService.java:141)
...
Caused by: java.lang.IllegalArgumentException: Authentication object cannot be null
```

#### To Reproduce

1. Go to Course Administration > Programming Exercise > Edit in Editor
2. Change a file and click save 
3. The file is not saved, the saving indicator won't stop turning

#### Expected behavior

Save should quickly save the file by WS communication.

#### Screenshots

![image](https://user-images.githubusercontent.com/28230611/64127340-7f4a6c00-cdb1-11e9-8512-7e6f96326906.png)

### Environment

Environment independent.

#### Additional context

n/a

#### Output in Web Console

n/a

**Comment by thilo-behnke** [comment]
I'm closing this issue now as the PR was merged.
