### ISSUE TITLE
Cannot remove courses with tutorial groups

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#8090]
### Describe the bug

We have to delete courses on a regular basis. During the current deletions, I encountered a problem during the deletion of a course with enabled tutorial groups.

```
2024-02-27 17:28:21.872 ERROR 1 --- [io-8080-exec-32] o.h.e.jdbc.batch.internal.BatchingBatch  : HHH000315: Exception executing batch [java.sql.BatchUpdateException: Cannot delete or update a parent row: a foreign key constraint fails (`artemis`.`tutorial_group`, CONSTRAINT `fk_tutorial_group_channel` FOREIGN KEY (`tutorial_group_channel_id`) REFERENCES `conversation` (`id`))], SQL: delete from conversation where id=?
2024-02-27 17:28:21.872  WARN 1 --- [io-8080-exec-32] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1451, SQLState: 23000
2024-02-27 17:28:21.872 ERROR 1 --- [io-8080-exec-32] o.h.engine.jdbc.spi.SqlExceptionHelper   : Cannot delete or update a parent row: a foreign key constraint fails (`artemis`.`tutorial_group`, CONSTRAINT `fk_tutorial_group_channel` FOREIGN KEY (`tutorial_group_channel_id`) REFERENCES `conversation` (`id`))
2024-02-27 17:28:21.898 ERROR 1 --- [io-8080-exec-32] o.z.problem.spring.common.AdviceTraits   : Internal Server Error

org.springframework.dao.DataIntegrityViolationException: could not execute batch; SQL [delete from conversation where id=?]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:276)
	......
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute batch
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:109)
	......
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:562)
	... 137 common frames omitted
Caused by: java.sql.BatchUpdateException: Cannot delete or update a parent row: a foreign key constraint fails (`artemis`.`tutorial_group`, CONSTRAINT `fk_tutorial_group_channel` FOREIGN KEY (`tutorial_group_channel_id`) REFERENCES `conversation` (`id`))
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:223)
	at com.mysql.cj.jdbc.ServerPreparedStatement.executeBatchSerially(ServerPreparedStatement.java:307)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:416)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:802)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:125)
	... 160 common frames omitted
Caused by: java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`artemis`.`tutorial_group`, CONSTRAINT `fk_tutorial_group_channel` FOREIGN KEY (`tutorial_group_channel_id`) REFERENCES `conversation` (`id`))
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:555)
	at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:339)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1054)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1003)
	at com.mysql.cj.jdbc.ServerPreparedStatement.executeBatchSerially(ServerPreparedStatement.java:279)
	... 165 common frames omitted
```

### To Reproduce

Was in production system. Couse has Tutorial groups.

### Expected behavior

Course should be deleted.

### Which version of Artemis are you seeing the problem on?

6.8.2

### What browsers are you seeing the problem on?

Firefox

### Additional context

If I delete all tutorial groups manually, I can delete the course afterwards.

**Comment by krusche** [comment]
Both tutorial group channels and iris settings are deleted as part of the `CourseService.delete` method.
We need more details what actually does not work. Ideally, we can reproduce this in a server test case.

**Comment by krusche** [comment]
Seems the issue is that the channel is deleted, but still references a tutorial group

`Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]: 2024-03-02 15:18:49.430 ERROR 1448057 --- [nio-8080-exec-7] o.h.e.jdbc.batch.internal.BatchingBatch  : HHH000315: Exception executing batch [java.sql.BatchUpdateException: Cannot delete or update a parent row: a foreign key constraint fails (`Artemis`.`tutorial_group`, CONSTRAINT `fk_tutorial_group_channel` FOREIGN KEY (`tutorial_group_channel_id`) REFERENCES `conversation` (`id`))], SQL: delete from conversation where id=?
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]: 2024-03-02 15:18:49.530  WARN 1448057 --- [nio-8080-exec-7] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1451, SQLState: 23000
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]: 2024-03-02 15:18:49.531 ERROR 1448057 --- [nio-8080-exec-7] o.h.engine.jdbc.spi.SqlExceptionHelper   : Cannot delete or update a parent row: a foreign key constraint fails (`Artemis`.`tutorial_group`, CONSTRAINT `fk_tutorial_group_channel` FOREIGN KEY (`tutorial_group_channel_id`) REFERENCES `conversation` (`id`))
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]: 2024-03-02 15:18:49.644 ERROR 1448057 --- [nio-8080-exec-7] o.z.problem.spring.common.AdviceTraits   : Internal Server Error
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]: org.springframework.dao.DataIntegrityViolationException: could not execute batch; SQL [delete from conversation where id=?]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]:         at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:276)
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]:         at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233)
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]:         at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:566)
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]:         at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743)
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]:         at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]:         at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:654)
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]:         at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:407)
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]:         at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]:         at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]:         at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:145)
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]:         at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]:         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:241)
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]:         at jdk.proxy2/jdk.proxy2.$Proxy329.deleteAllByCourseId(Unknown Source)
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]:         at de.tum.in.www1.artemis.service.CourseService.deleteConversationsOfCourse(CourseService.java:435)
Mar 02 15:18:49 artemis-test0.artemis.in.tum.de java[1448057]:         at de.tum.in.www1.artemis.service.CourseService.delete(CourseService.java:412)
`

**Comment by krusche** [comment]
a workaround is to first delete the tutorial groups manually, which also deletes their corresponding channels correctly and then delete the course

**Comment by krusche** [comment]
Here is a draft PR that hopefully fixes the issue: https://github.com/ls1intum/Artemis/pull/8113
We need to add server tests
