### ISSUE TITLE
Docker connection issues using LocalCI and LocalVC

### ISSUE THREAD

**Issue by julfeder** [ls1intum/Artemis#8330]
### Describe the bug

I am trying to set up a local development environment to try out and get to know Artemis. I can get both server and client running along with a MySQL Database in a docker container but automated assessment of programming exercises just won't work using LocalCI and LocalVC. I am using Windows 11 by the way.

For configuration I have set `docker-connection-uri: tcp://localhost:2375` in `application-localci.yml` and have enabled "Expose daemon on tcp://localhost:2375 without TLS" in Docker Desktop. I have also set user-management to `use-external: false`.
I run server and client with the corresponding run configurations in  IntelliJ IDEA 2023.2.5 (Ultimate Edition), so `Artemis (Server, LocalVC & LocalCI)` and  `Artemis (Client)`. I run a MySQL docker container with `docker compose -f .\docker\mysql.yml up`.
After everything is up and running I can log in as artemis_admin and create a course and a programming exercise in that course (using the "Sorting with the Strategy Pattern" exercise template). This is where the issues arise:

When trying to clone the git repo `http://artemis_admin@localhost:8000/git/TESTKURSTEST2/testkurstest2-artemis_admin.git` git gives me `fatal: unable to access 'http://localhost:8000/git/TESTKURSTEST2/testkurstest2-artemis_admin.git/': Failed to connect to localhost port 8000 after 2286 ms: Couldn't connect to server`.

The web editor I can use fine but after hitting "Submit" I get an error toast saying "The result for your last submission is not available. Please submit your code again" and the server console shows multiple Exceptions, all essentially saying "Could not initialize class `com.github.dockerjava.transport.DomainSocket`". I will put a more extensive log in the field "Relevant log output".

### To Reproduce

1. Be on Windows
2. Set `docker-connection-uri: tcp://localhost:2375` in `application-localci.yml` and have enabled "Expose daemon on tcp://localhost:2375 without TLS" in Docker Desktop
3. Run a MySQL docker container
4. Run `Artemis (Server, LocalVC & LocalCI)` and  `Artemis (Client)` run configurations in IntelliJ IDEA
5. Create course
6. Create programming exercise in that course
7. Try to clone the exercise repository or submit any changes in the online editor.

### Expected behavior

When trying to clone the exercise repo it should successfully clone.
When hitting submit in the online editor, the code should be built, tested, and the results reported back to the user.

### Which version of Artemis are you seeing the problem on?

6.9.5

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
2024-04-07 13:34:15.622  INFO 16500 --- [nio-8080-exec-6] t.i.w.a.s.p.ProgrammingSubmissionService : Create new programmingSubmission with commitHash: af27bad076c2e91a7db8f90c23fa8d18e8b68c87 for participation 6
2024-04-07 13:34:15.622 DEBUG 16500 --- [Artemis.event-1] d.t.i.w.a.aop.logging.LoggingAspect      : Exit: de.tum.in.www1.artemis.service.WebsocketMessagingService.sendMessage() with result = java.util.concurrent.CompletableFuture@51e94c8a[Not completed]
2024-04-07 13:34:15.622 ERROR 16500 --- [ocal-ci-build-1] d.t.i.w.a.aop.logging.LoggingAspect      : Exception in de.tum.in.www1.artemis.service.connectors.localci.buildagent.BuildJobExecutionService.runBuildJob() with cause = 'java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Error looking up function 'write': Die angegebene Prozedur wurde nicht gefunden.
 [in thread "pool-10-thread-1"]' and exception = 'Could not initialize class com.github.dockerjava.transport.DomainSocket'

java.lang.NoClassDefFoundError: Could not initialize class com.github.dockerjava.transport.DomainSocket
	at com.github.dockerjava.transport.UnixSocket.get(UnixSocket.java:29)
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl$2.createSocket(ApacheDockerHttpClientImpl.java:153)
	at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:125)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:396)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:158)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:168)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:136)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:190)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:133)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:191)
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:9)
	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
	at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:202)
	at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:74)
	at com.github.dockerjava.core.exec.InspectImageCmdExec.execute(InspectImageCmdExec.java:28)
	at com.github.dockerjava.core.exec.InspectImageCmdExec.execute(InspectImageCmdExec.java:13)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
	at com.github.dockerjava.core.command.InspectImageCmdImpl.exec(InspectImageCmdImpl.java:39)
	at de.tum.in.www1.artemis.service.connectors.localci.buildagent.LocalCIDockerService.pullDockerImage(LocalCIDockerService.java:88)
	at de.tum.in.www1.artemis.service.connectors.localci.buildagent.LocalCIDockerService$$FastClassBySpringCGLIB$$41ac3e42.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at de.tum.in.www1.artemis.aop.logging.LoggingAspect.logAround(LoggingAspect.java:86)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
	at de.tum.in.www1.artemis.service.connectors.localci.buildagent.LocalCIDockerService$$EnhancerBySpringCGLIB$$81762432.pullDockerImage(<generated>)
	at de.tum.in.www1.artemis.service.connectors.localci.buildagent.BuildJobExecutionService.runBuildJob(BuildJobExecutionService.java:106)
	at de.tum.in.www1.artemis.service.connectors.localci.buildagent.BuildJobExecutionService$$FastClassBySpringCGLIB$$5f3e656a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at de.tum.in.www1.artemis.aop.logging.LoggingAspect.logAround(LoggingAspect.java:86)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707)
	at de.tum.in.www1.artemis.service.connectors.localci.buildagent.BuildJobExecutionService$$EnhancerBySpringCGLIB$$a78a52aa.runBuildJob(<generated>)
	at de.tum.in.www1.artemis.service.connectors.localci.buildagent.BuildJobManagementService.lambda$executeBuildJob$1(BuildJobManagementService.java:111)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Error looking up function 'write': Die angegebene Prozedur wurde nicht gefunden.
 [in thread "pool-10-thread-1"]
	at com.sun.jna.Function.<init>(Function.java:252)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:620)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:596)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:582)
	at com.sun.jna.Native.register(Native.java:1904)
	at com.sun.jna.Native.register(Native.java:1775)
	at com.sun.jna.Native.register(Native.java:1493)
	at com.github.dockerjava.transport.DomainSocket.<clinit>(DomainSocket.java:54)
	at com.github.dockerjava.transport.UnixSocket.get(UnixSocket.java:29)
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl$2.createSocket(ApacheDockerHttpClientImpl.java:153)
	at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:125)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:396)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:158)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:168)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:136)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:190)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:133)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:191)
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:9)
	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
	at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:202)
	at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:74)
	at com.github.dockerjava.core.exec.ListContainersCmdExec.execute(ListContainersCmdExec.java:44)
	at com.github.dockerjava.core.exec.ListContainersCmdExec.execute(ListContainersCmdExec.java:15)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
	at de.tum.in.www1.artemis.service.connectors.localci.buildagent.LocalCIDockerService.lambda$applicationReady$2(LocalCIDockerService.java:71)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	... 3 common frames omitted
```

**Comment by tobias-lippert** [comment]
Could you maybe post your application-local.yml file (make sure to remove any credentials beforehand)? I assume it's a config issue as this error arises if the application cannot connect to the docker host.

**Comment by julfeder** [comment]
> @julfeder Could you maybe post your application-local.yml file (make sure to remove any credentials beforehand)? I assume it's a config issue as this error arises if the application cannot connect to the docker host.

My application-local.yml is fairly minimal, see below:
```
artemis:
  user-management:
    use-external: false
  continuous-integration:
    docker-connection-uri: tcp://localhost:2375
```
The issue has (partly) fixed itself in the meantime -- I checked out version 6.9.6 and autograding in the online editor works now!
What still does not work for me is cloning the exercise repo with git (see error in the original post). This probably is a different issue altogether or simply user error on my side but do you have any idea what could cause this?

**Comment by julfeder** [comment]
The git clone issue was user error. I somehow did not see that the version-control url was set to 8000 instead of 8080 all this time.

**Comment by GooeyFlyer** [comment]
@julfeder I have run into the same issue. Where were you setting the version-control url?

**Comment by julianfeder** [comment]
> @julfeder I have run into the same issue. Where were you setting the version-control url?

I have created a application-local.yml as is recommended in the [documentation](https://docs.artemis.cit.tum.de/dev/setup/server.html). In there you can override settings from the various other config files.

This is my application-local.yml:
```YAML
artemis:
  user-management:
    use-external: false
  continuous-integration:
    # The Docker connection URI to be used by docker-java to connect to the system's Docker installation. Use "unix:///var/run/docker.sock" for Unix based systems and "tcp://localhost:2375" for Windows systems.
    docker-connection-uri: tcp://localhost:2375
    # As I use the local CI and VC I set this to the same port as the Artemis server application
  version-control:
    url: http://localhost:8080
```
