### ISSUE TITLE
Cannot delete participation/exercise/course due to build_log_statistics_entry

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#9272]
### Describe the bug

Deleting a course that has submissions fails.

### To Reproduce

1. Have a course with some student submissions.
2. As admin, try to delete the course.

### Expected behavior

The course can be deleted without errors.

### Which version of Artemis are you seeing the problem on?

7.5.1

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
org.springframework.dao.DataIntegrityViolationException: could not execute batch [Batch entry 0 delete from submission where id=('32201'::int8) was aborted: ERROR: update or delete on table "submission" violates foreign key constraint "FKarrnc5l01jjyixrw6jbu18k6b" on table "build_log_statistics_entry"
  Detail: Key (id)=(32201) is still referenced from table "build_log_statistics_entry".  Call getNextException to see other errors in the batch.] [delete from submission where id=?]; SQL [delete from submission where id=?]; constraint [FKarrnc5l01jjyixrw6jbu18k6b]
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:290)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:241)
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:566)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:795)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:758)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:663)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:413)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:165)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:223)
        at jdk.proxy2/jdk.proxy2.$Proxy291.deleteById(Unknown Source)
        at de.tum.in.www1.artemis.service.ParticipationService.lambda$deleteResultsAndSubmissionsOfParticipation$17(ParticipationService.java:872)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at de.tum.in.www1.artemis.service.ParticipationService.deleteResultsAndSubmissionsOfParticipation(ParticipationService.java:864)
        at de.tum.in.www1.artemis.service.programming.ProgrammingExerciseService.delete(ProgrammingExerciseService.java:811)
        at de.tum.in.www1.artemis.service.ExerciseDeletionService.delete(ExerciseDeletionService.java:195)
        at de.tum.in.www1.artemis.service.CourseService.deleteExercisesOfCourse(CourseService.java:529)
        at de.tum.in.www1.artemis.service.CourseService.delete(CourseService.java:455)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:716)
        at de.tum.in.www1.artemis.service.CourseService$$SpringCGLIB$$0.delete(<generated>)
        at de.tum.in.www1.artemis.web.rest.admin.AdminCourseResource.deleteCourse(AdminCourseResource.java:179)
```

**Comment by b-fein** [comment]
See #10351. Was fixed with the linked PR.
