### ISSUE TITLE
`Programming exercises`: Hidden Files in Online Editor cannot be removed or created

### ISSUE THREAD

**Issue by BaumiCoder** [ls1intum/Artemis#9309]
### Describe the bug

Removing or creating a file in the online editor, which is a hidden one (i.e. name starts with a dot). Triggers an error `Illegal argument during operation or file already exists`.

### To Reproduce

1. Go to an Online Editor e.g. Edit the test repository of a programming exercise
2. Create a hidden file e.g. `.gitkeep` OR Remove a hidden file e.g. `.gitignore`
3. You get an error message

### Expected behavior

The deleting or creating works without an error message.

### Screenshots

![Delete hidden file shows error message](https://github.com/user-attachments/assets/1f628190-7a90-49fc-9251-e1117ff06b94)

### Which version of Artemis are you seeing the problem on?

7.5.1 and Branch: develop • Commit Hash: 85dd4ab • Committer Date: Wed, 11 Sep 2024

### What browsers are you seeing the problem on?

Microsoft Edge, Firefox

### Additional context

Showing hidden files in the Online Editor was introduced with #4868 (Issue) / #8488 (Pull Request)

### Relevant log output

```
2024-09-11T05:37:24.350Z ERROR 1 --- [Artemis] [cat-handler-467] ProgrammingExerciseParticipationResource : Illegal argument during operation or file already exists
java.lang.IllegalArgumentException: null
        at de.tum.in.www1.artemis.service.programming.RepositoryService.deleteFile(RepositoryService.java:448)
        at de.tum.in.www1.artemis.web.rest.repository.RepositoryResource.lambda$deleteFile$5(RepositoryResource.java:228)
        at de.tum.in.www1.artemis.web.rest.repository.RepositoryResource.executeAndCheckForExceptions(RepositoryResource.java:355)
        at de.tum.in.www1.artemis.web.rest.repository.RepositoryResource.deleteFile(RepositoryResource.java:226)
        at de.tum.in.www1.artemis.web.rest.repository.RepositoryProgrammingExerciseParticipationResource.deleteFile(RepositoryProgrammingExerciseParticipationResource.java:343)
```

**Comment by b-fein** [comment]
resolved by #10655
